buildscript {
    ext {
        defaultApplicationId = "thanhdnh.ueh.edu.articleapp"
    }

    repositories {
        google()
        mavenCentral()
    }
}

plugins {
    id 'com.android.application' version '9.3.0' apply false
}

ext {
    defaultApplicationId = 'thanhdnh.ueh.edu.articleapp'
    defaultApplicationId1 = defaultApplicationId
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register("clean", Delete) {
    delete layout.buildDirectory.asFile.get()
}